name: Python package

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install pdm
        run: python -m pip install pdm==2.7.4
      - name: Check pdm.lock
        run: pdm lock --check
      - name: Install dependencies
        run: pdm install
      - name: Run linters
        run: pdm run linters-check
      - name: Run tests
        run: pdm run unit-tests
